Readme
AlbianWarp/AlbianWarpClient pull request #19
Opened 2018-04-19 20:05 UTC by KeyboardInterrupt

2018-04-19 20:37 UTC, Amaikokonut requested changes
The rest of this looks good to me!

2018-04-19 20:37 UTC, Amaikokonut commented on CONTRIBUTING.md
> +reported by contacting the project team at [INSERT EMAIL ADDRESS]. All
Which email address?

2018-04-20 04:27 UTC, KeyboardInterrupt commented
This Pull Request relates to Issue No. #4 (Add a README.md and LICENSE.md)

2018-04-20 05:14 UTC, Amaikokonut approved these changes

2018-04-20 05:22 UTC, merged